"""Fail-closed file classification for Lean Code metrics."""

from __future__ import annotations

from pathlib import Path

from ai_sdlc.core.lean_code_models import FileClassification

_DECLARATIVE_SUFFIXES = {".json", ".yaml", ".yml", ".toml", ".ini", ".csv", ".xml"}
_CODE_SUFFIXES = {".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".go", ".rs", ".cs"}
_GENERATED_MARKERS = (b"@generated", b"generated by", b"code generated", b"do not edit")
_VENDORED_MARKERS = (
    b"vendored from",
    b"upstream source",
    b"third-party source",
    b"third party source",
)


def classify_file(path: str, content: bytes, binary: bool) -> FileClassification:
    """Classify special paths only when their content carries provenance evidence."""

    normalized = path.replace("\\", "/").lower()
    parts = set(normalized.split("/"))
    suffix = Path(normalized).suffix
    header = content[:4096].lower()
    vendored_path = bool(parts & {"vendor", "vendored", "third_party", "node_modules"})
    generated_path = "generated" in parts or normalized.endswith(
        (".generated.ts", ".min.js")
    )
    if vendored_path:
        return (
            FileClassification.VENDORED
            if any(marker in header for marker in _VENDORED_MARKERS)
            else FileClassification.UNKNOWN
        )
    if generated_path:
        return (
            FileClassification.GENERATED
            if any(marker in header for marker in _GENERATED_MARKERS)
            else FileClassification.UNKNOWN
        )
    if "fixtures" in parts or "fixture" in parts:
        return FileClassification.FIXTURE
    if "__snapshots__" in parts or suffix in {".snap", ".snapshot"}:
        return FileClassification.SNAPSHOT
    if suffix in _DECLARATIVE_SUFFIXES:
        return FileClassification.DECLARATIVE
    if (
        normalized.startswith("tests/")
        or "/tests/" in normalized
        or Path(normalized).name.startswith("test_")
    ):
        return FileClassification.HANDWRITTEN_TEST
    if suffix in _CODE_SUFFIXES and not binary:
        return FileClassification.HANDWRITTEN_PRODUCT
    return FileClassification.UNKNOWN


__all__ = ["classify_file"]
