"""Lean Code 分类、指标与风险组合的行为测试。"""

from __future__ import annotations

import hashlib
import subprocess
import sys
import time
from pathlib import Path

from ai_sdlc.core.implementation_models import ImplementationInput
from ai_sdlc.core.implementation_store import implementation_artifacts
from ai_sdlc.core.lean_code_evaluator import (
    LeanEvaluationOptions,
    evaluate_lean_code,
)
from ai_sdlc.core.lean_code_models import (
    FileClassification,
    LeanException,
    LeanPolicy,
    RegressionEvidence,
)
from ai_sdlc.core.lean_code_policy import stable_artifact_digest
from ai_sdlc.core.lean_code_regression import (
    LeanRegressionOptions,
    capture_regression_phase,
)
from ai_sdlc.core.loop_artifacts import LoopArtifactStore
from ai_sdlc.core.loop_models import LoopRun, LoopStatus, LoopType
from ai_sdlc.core.pr_review_models import FindingSeverity
from ai_sdlc.core.source_snapshot import SourceSnapshotOptions, build_source_snapshot
from ai_sdlc.models.work import WorkType


def test_same_frozen_input_produces_the_same_stable_report_digest(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/app.py", "def _value():\n    return 1\n")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )

    first = _evaluate(tmp_path, scope=("src/app.py",), snapshot=snapshot)
    time.sleep(1.05)
    second = _evaluate(tmp_path, scope=("src/app.py",), snapshot=snapshot)

    assert stable_artifact_digest(first) == stable_artifact_digest(second)


def test_historical_600_line_file_is_advisory_only(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/legacy.py": _simple_lines(600)})
    lines = _simple_lines(600).splitlines()
    lines[300] = "value_300 = 999"
    _write(tmp_path, "src/legacy.py", "\n".join(lines) + "\n")

    report = _evaluate(tmp_path, scope=("src/legacy.py",))

    assert _severities(report, "lean.file-budget") == {FindingSeverity.ADVISORY}
    assert report.status == LoopStatus.PASSED


def test_generated_401_line_file_is_not_in_product_budget(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(
        tmp_path,
        "generated/client.py",
        "# Code generated by schema compiler. DO NOT EDIT.\n" + _simple_lines(401),
    )

    report = _evaluate(tmp_path, scope=("generated/client.py",))

    metric = report.metrics.files[0]
    assert metric.classification == "generated"
    assert report.metrics.classification_counts["generated"] == 1
    assert _severities(report, "lean.file-budget") == set()


def test_generated_path_without_provenance_fails_closed(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "generated/handwritten.py", "def hidden_logic():\n    return 1\n")

    report = _evaluate(tmp_path, scope=("generated/handwritten.py",))

    assert report.metrics.files[0].classification == "unknown"
    assert report.status == LoopStatus.NEEDS_USER


def test_51_line_low_complexity_function_is_advisory(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    body = "\n".join(f"    value += {index}" for index in range(51))
    _write(
        tmp_path,
        "src/app.py",
        f"def _process():\n    value = 0\n{body}\n    return value\n",
    )

    report = _evaluate(tmp_path, scope=("src/app.py",))

    assert _severities(report, "lean.function-budget") == {FindingSeverity.ADVISORY}
    assert report.status == LoopStatus.PASSED


def test_oversized_complex_function_is_required(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    branches = "\n".join(
        f"    if value == {index}:\n        value += 1" for index in range(12)
    )
    padding = "\n".join("    value += 1" for _ in range(30))
    _write(
        tmp_path,
        "src/app.py",
        f"def _process(value):\n{branches}\n{padding}\n    return value\n",
    )

    report = _evaluate(tmp_path, scope=("src/app.py",))

    assert FindingSeverity.REQUIRED in _severities(report, "lean.function-risk")
    assert report.status == LoopStatus.NEEDS_FIX


def test_enforcement_modes_have_distinct_required_finding_statuses(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/api.py", "def unused_public():\n    return 1\n")

    report_mode = _evaluate(
        tmp_path, scope=("src/api.py",), policy=LeanPolicy(enforcement_mode="report")
    )
    warning_mode = _evaluate(
        tmp_path,
        scope=("src/api.py",),
        policy=LeanPolicy(enforcement_mode="warning"),
    )
    blocking_mode = _evaluate(
        tmp_path,
        scope=("src/api.py",),
        policy=LeanPolicy(enforcement_mode="blocking"),
    )

    assert report_mode.status == LoopStatus.PASSED
    assert warning_mode.status == LoopStatus.NEEDS_FIX
    assert blocking_mode.status == LoopStatus.BLOCKED


def test_declarative_schema_is_not_mechanically_split(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "schemas/routes.yaml", _simple_lines(500))

    report = _evaluate(tmp_path, scope=("schemas/routes.yaml",))

    assert report.metrics.files[0].classification == "declarative"
    assert not report.findings
    assert report.status == LoopStatus.PASSED


def test_unknown_changed_file_fails_closed_to_needs_user(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/runtime.mystery", "opaque\n")

    report = _evaluate(tmp_path, scope=("src/runtime.mystery",))

    assert report.metrics.files[0].classification == "unknown"
    assert report.status == LoopStatus.NEEDS_USER
    assert _severities(report, "lean.classification-unknown") == {
        FindingSeverity.ADVISORY
    }


def test_feature_with_only_declared_scope_passes(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/app.py", "def _accepted():\n    return 1\n")

    report = _evaluate(tmp_path, scope=("src/app.py",))

    assert report.status == LoopStatus.PASSED
    assert not report.blocking_findings


def test_new_public_helper_with_fewer_than_three_callers_is_required(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path)
    _write(
        tmp_path,
        "src/factory.py",
        "def build_future_strategy():\n    return object()\n",
    )

    report = _evaluate(tmp_path, scope=("src/factory.py",))

    assert _severities(report, "lean.public-callers") == {FindingSeverity.REQUIRED}
    assert report.status == LoopStatus.NEEDS_FIX


def test_scope_drift_is_blocker(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/accepted.py", "VALUE = 1\n")
    _write(tmp_path, "src/unrelated.py", "VALUE = 2\n")

    report = _evaluate(tmp_path, scope=("src/accepted.py",))

    assert _severities(report, "lean.scope-drift") == {FindingSeverity.BLOCKER}
    assert report.status == LoopStatus.NEEDS_FIX


def test_bugfix_without_regression_evidence_needs_fix(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
    )

    assert _severities(report, "lean.bugfix-regression") == {FindingSeverity.REQUIRED}
    assert report.status == LoopStatus.NEEDS_FIX


def test_bugfix_with_bound_red_green_evidence_passes(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    evidence = _regression_evidence(tmp_path)
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py", "tests/regression_probe.py"),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
        evidence=(evidence,),
    )

    assert _severities(report, "lean.bugfix-regression") == set()
    assert report.status == LoopStatus.PASSED


def test_stale_bugfix_evidence_is_blocker(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    evidence = _regression_evidence(tmp_path)
    _write(tmp_path, "src/bug.py", "def _value():\n    return 2\n")

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py", "tests/regression_probe.py"),
        work_type=WorkType.PRODUCTION_ISSUE,
        evidence=(evidence,),
    )

    assert _severities(report, "lean.bugfix-evidence-stale") == {
        FindingSeverity.BLOCKER
    }


def test_self_reported_bugfix_evidence_without_bound_outputs_is_blocker(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )
    evidence = RegressionEvidence(
        test_id="fake",
        command_argv=["pytest", "tests/test_bug.py::test_value"],
        red_source="before-fix",
        red_diff_hash="sha256:red",
        red_exit_code=1,
        green_source="after-fix",
        green_diff_hash=snapshot.diff_hash,
        green_exit_code=0,
        failure_signature="assertion:anything",
        red_output_digest="sha256:anything",
        green_output_digest="sha256:anything",
        toolchain_fingerprint="anything",
        test_refs=["tests/test_bug.py::test_value"],
    )

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
        evidence=(evidence,),
    )

    assert _severities(report, "lean.bugfix-evidence-invalid") == {
        FindingSeverity.BLOCKER
    }


def test_non_python_semantic_metrics_fail_closed_without_false_zero(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/app.ts", "export function value() { return 1; }\n")

    report = _evaluate(tmp_path, scope=("src/app.ts",))

    metric = report.metrics.files[0]
    assert metric.capability == "unsupported"
    assert metric.functions == []
    assert report.metrics.unsupported_semantic_files == ["src/app.ts"]
    assert report.status == LoopStatus.NEEDS_USER


def test_exact_duplicate_function_candidates_increase_combined_risk(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path)
    body = "\n".join("    value += 1" for _ in range(51))
    source = f"def _process():\n    value = 0\n{body}\n    return value\n"
    _write(tmp_path, "src/first.py", source)
    _write(tmp_path, "src/second.py", source)

    report = _evaluate(tmp_path, scope=("src/*.py",))

    assert report.metrics.duplicate_candidates
    assert all(
        function.duplicate_count == 2
        for metric in report.metrics.files
        for function in metric.functions
    )
    assert _severities(report, "lean.function-risk") == {FindingSeverity.REQUIRED}


def test_generated_file_growth_beyond_task_budget_is_required(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    for index in range(6):
        _write(
            tmp_path,
            f"generated/client_{index}.py",
            "# Code generated by schema compiler. DO NOT EDIT.\nVALUE = 1\n",
        )

    report = _evaluate(tmp_path, scope=("generated/*.py",))

    assert _severities(report, "lean.generated-scope") == {FindingSeverity.REQUIRED}
    assert report.status == LoopStatus.NEEDS_FIX


def test_valid_structured_exception_keeps_finding_and_accepts_risk(
    tmp_path: Path,
) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )
    first = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
    )
    finding = next(
        item for item in first.findings if item.rule_id == "lean.bugfix-regression"
    )
    evidence_path = tmp_path / "evidence" / "exception.txt"
    _write(tmp_path, "evidence/exception.txt", "approved risk\n")
    evidence_digest = "sha256:" + hashlib.sha256(evidence_path.read_bytes()).hexdigest()
    exception = LeanException(
        exception_id="EX-1",
        rule_id=finding.rule_id,
        path="src/bug.py",
        stable_signature=finding.stable_signature,
        reason="Target environment cannot reproduce the issue before the deadline.",
        owner="release-owner",
        approver="quality-owner",
        evidence_refs=["evidence/exception.txt"],
        evidence_digests={"evidence/exception.txt": evidence_digest},
        scope=["src/bug.py"],
        policy_digest=stable_artifact_digest(LeanPolicy()),
        base_commit=snapshot.base_commit,
        head_commit=snapshot.head_commit,
        diff_hash=snapshot.diff_hash,
        evaluation_digest=stable_artifact_digest(first),
        expires_at="2099-01-01T00:00:00Z",
    )

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
        exceptions=(exception,),
        previous_report_digest=stable_artifact_digest(first),
    )

    retained = next(item for item in report.findings if item.rule_id == finding.rule_id)
    assert retained.resolution == "waived"
    assert report.exception_ids == ["EX-1"]
    assert report.risk_accepted is True
    assert report.status == LoopStatus.PASSED


def test_exception_with_wrong_evaluation_digest_is_blocker(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )
    first = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
    )
    finding = next(
        item for item in first.findings if item.rule_id == "lean.bugfix-regression"
    )
    _write(tmp_path, "evidence/exception.txt", "approved risk\n")
    exception = LeanException(
        exception_id="EX-WRONG-EVALUATION",
        rule_id=finding.rule_id,
        path="src/bug.py",
        stable_signature=finding.stable_signature,
        reason="A wrong evaluation digest must not authorize the current finding.",
        owner="release-owner",
        approver="quality-owner",
        evidence_refs=["evidence/exception.txt"],
        evidence_digests={
            "evidence/exception.txt": _file_digest(tmp_path / "evidence/exception.txt")
        },
        scope=["src/bug.py"],
        policy_digest=stable_artifact_digest(LeanPolicy()),
        base_commit=snapshot.base_commit,
        head_commit=snapshot.head_commit,
        diff_hash=snapshot.diff_hash,
        evaluation_digest="sha256:wrong",
        expires_at="2099-01-01T00:00:00Z",
    )

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
        exceptions=(exception,),
        previous_report_digest=stable_artifact_digest(first),
    )

    assert _severities(report, "lean.exception-invalid") == {FindingSeverity.BLOCKER}


def test_invalid_structured_exception_is_blocker(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/bug.py": "def _value():\n    return 0\n"})
    _write(tmp_path, "src/bug.py", "def _value():\n    return 1\n")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-unstaged")
    )
    exception = LeanException(
        exception_id="EX-BAD",
        rule_id="lean.bugfix-regression",
        path="src/bug.py",
        stable_signature="sha256:not-the-current-finding",
        reason="Invalid evidence must not authorize closure.",
        owner="release-owner",
        approver="quality-owner",
        evidence_refs=["evidence/missing.txt"],
        evidence_digests={"evidence/missing.txt": "sha256:missing"},
        scope=["src/bug.py"],
        policy_digest=stable_artifact_digest(LeanPolicy()),
        base_commit=snapshot.base_commit,
        head_commit=snapshot.head_commit,
        diff_hash=snapshot.diff_hash,
        evaluation_digest="sha256:prior-evaluation",
        expires_at="2099-01-01T00:00:00Z",
    )

    report = _evaluate(
        tmp_path,
        scope=("src/bug.py",),
        work_type=WorkType.PRODUCTION_ISSUE,
        snapshot=snapshot,
        exceptions=(exception,),
    )

    assert _severities(report, "lean.exception-invalid") == {FindingSeverity.BLOCKER}
    assert report.risk_accepted is False
    assert report.status == LoopStatus.NEEDS_FIX


def test_patch_source_metrics_use_patched_python_content(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/app.py": "VALUE = 1\n"})
    _write(
        tmp_path,
        "src/app.py",
        "VALUE = 1\n\ndef _patched_value():\n    return VALUE\n",
    )
    patch_text = _git(tmp_path, "diff", "--binary", "--", "src/app.py")
    _write(tmp_path, "change.patch", patch_text + "\n")
    _git(tmp_path, "restore", "--worktree", "src/app.py")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(
            root=tmp_path,
            source_kind="patch",
            patch_file="change.patch",
        )
    )

    report = _evaluate(tmp_path, scope=("src/app.py",), snapshot=snapshot)

    metric = report.metrics.files[0]
    assert metric.added_lines == 3
    assert [item.symbol for item in metric.functions] == ["_patched_value"]
    assert report.status == LoopStatus.PASSED


def test_git_range_callers_are_read_from_frozen_head(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    base = _git(tmp_path, "rev-parse", "HEAD")
    _write(tmp_path, "src/api.py", "def build_value():\n    return 1\n")
    _write(
        tmp_path,
        "src/callers.py",
        """from src.api import build_value

def _caller_a():
    return build_value()

def _caller_b():
    return build_value()

def _caller_c():
    return build_value()
""",
    )
    _git(tmp_path, "add", ".")
    _git(tmp_path, "commit", "-m", "add frozen callers")
    head = _git(tmp_path, "rev-parse", "HEAD")
    _git(tmp_path, "switch", "--detach", base)
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(
            root=tmp_path,
            source_kind="local-git-range",
            base_ref=base,
            head_ref=head,
        )
    )

    report = _evaluate(tmp_path, scope=("src/*.py",), snapshot=snapshot)

    helper = report.metrics.files[0].functions[0]
    assert helper.symbol == "build_value"
    assert helper.caller_count == 3
    assert _severities(report, "lean.public-callers") == set()


def test_src_layout_imports_resolve_to_current_public_callers(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/pkg/api.py", "def build_value():\n    return 1\n")
    _write(
        tmp_path,
        "src/pkg/callers.py",
        """from pkg.api import build_value

def _caller_a():
    return build_value()

def _caller_b():
    return build_value()

def _caller_c():
    return build_value()
""",
    )

    report = _evaluate(tmp_path, scope=("src/pkg/*.py",))

    helper = next(
        function
        for metric in report.metrics.files
        for function in metric.functions
        if function.symbol == "build_value"
    )
    assert helper.caller_count == 3
    assert _severities(report, "lean.public-callers") == set()


def test_nested_function_call_counts_only_innermost_caller(tmp_path: Path) -> None:
    _init_repo(tmp_path)
    _write(tmp_path, "src/api.py", "def build_value():\n    return 1\n")
    _write(
        tmp_path,
        "src/callers.py",
        """from src.api import build_value

def _outer():
    def _middle():
        def _inner():
            return build_value()
        return _inner()
    return _middle()
""",
    )

    report = _evaluate(tmp_path, scope=("src/*.py",))

    helper = next(
        function
        for metric in report.metrics.files
        for function in metric.functions
        if function.symbol == "build_value"
    )
    assert helper.caller_count == 1
    assert _severities(report, "lean.public-callers") == {FindingSeverity.REQUIRED}


def test_unrelated_same_name_calls_do_not_satisfy_public_caller_budget(
    tmp_path: Path,
) -> None:
    noise = "\n".join(
        f"def _noise_{index}():\n    return build_value()" for index in range(3)
    )
    _init_repo(tmp_path, {"src/noise.py": noise + "\n"})
    _write(tmp_path, "src/api.py", "def build_value():\n    return 1\n")

    report = _evaluate(tmp_path, scope=("src/api.py",))

    helper = report.metrics.files[0].functions[0]
    assert helper.caller_count == 0
    assert _severities(report, "lean.public-callers") == {FindingSeverity.REQUIRED}


def test_pure_rename_does_not_create_a_new_public_symbol(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/old_api.py": "def build_value():\n    return 1\n"})
    _git(tmp_path, "mv", "src/old_api.py", "src/new_api.py")
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(root=tmp_path, source_kind="local-staged")
    )

    report = _evaluate(tmp_path, scope=("src/new_api.py",), snapshot=snapshot)

    helper = report.metrics.files[0].functions[0]
    assert helper.is_new is False
    assert _severities(report, "lean.public-callers") == set()


def test_patch_pure_rename_does_not_create_a_new_public_symbol(tmp_path: Path) -> None:
    _init_repo(tmp_path, {"src/old_api.py": "def build_value():\n    return 1\n"})
    _write(
        tmp_path,
        "rename.patch",
        "\n".join(
            (
                "diff --git a/src/old_api.py b/src/new_api.py",
                "similarity index 100%",
                "rename from src/old_api.py",
                "rename to src/new_api.py",
                "",
            )
        ),
    )
    snapshot = build_source_snapshot(
        SourceSnapshotOptions(
            root=tmp_path, source_kind="patch", patch_file="rename.patch"
        )
    )

    report = _evaluate(tmp_path, scope=("src/new_api.py",), snapshot=snapshot)

    helper = report.metrics.files[0].functions[0]
    assert snapshot.renamed_files == {"src/new_api.py": "src/old_api.py"}
    assert helper.is_new is False
    assert _severities(report, "lean.public-callers") == set()


def test_deleted_generated_file_keeps_before_view_provenance(tmp_path: Path) -> None:
    _init_repo(
        tmp_path,
        {
            "generated/client.py": "# Code generated by schema; DO NOT EDIT.\nVALUE = 1\n"
        },
    )
    (tmp_path / "generated" / "client.py").unlink()

    report = _evaluate(tmp_path, scope=("generated/client.py",))

    metric = report.metrics.files[0]
    assert metric.classification == FileClassification.GENERATED
    assert report.status == LoopStatus.PASSED


def _evaluate(
    root: Path,
    *,
    scope: tuple[str, ...],
    work_type: WorkType = WorkType.NEW_REQUIREMENT,
    snapshot=None,
    evidence: tuple[RegressionEvidence, ...] = (),
    exceptions: tuple[LeanException, ...] = (),
    previous_report_digest: str = "",
    policy: LeanPolicy | None = None,
):
    source = snapshot or build_source_snapshot(
        SourceSnapshotOptions(root=root, source_kind="local-unstaged")
    )
    return evaluate_lean_code(
        LeanEvaluationOptions(
            root=root,
            loop_id="impl-test",
            work_item_id="WI-TEST",
            work_type=work_type,
            source_snapshot=source,
            policy=policy or LeanPolicy(),
            declared_scope=scope,
            task_refs=("specs/WI-TEST/tasks.md",),
            acceptance_refs=("AC-1",),
            regression_evidence=evidence,
            exceptions=exceptions,
            previous_report_digest=previous_report_digest,
        )
    )


def _severities(report, rule_id: str) -> set[FindingSeverity]:
    return {
        FindingSeverity(finding.severity)
        for finding in report.findings
        if finding.rule_id == rule_id
    }


def _simple_lines(count: int) -> str:
    return "\n".join(f"value_{index} = {index}" for index in range(count)) + "\n"


def _regression_evidence(root: Path) -> RegressionEvidence:
    signature = "assertion:expected-1-got-0"
    _seed_execution_loop(root)
    _write(
        root,
        "tests/regression_probe.py",
        "from pathlib import Path\n"
        "source = Path('src/bug.py').read_text(encoding='utf-8')\n"
        f"print({signature!r}) if 'return 1' not in source else print('passed')\n"
        "raise SystemExit(0 if 'return 1' in source else 1)\n",
    )
    green_source = (root / "src" / "bug.py").read_text("utf-8")
    _write(root, "src/bug.py", "def _value():\n    return 0\n")
    options = {
        "root": root,
        "loop_id": "impl-test",
        "test_id": "test-value",
        "test_symbol": "tests.regression_probe",
        "command_argv": (sys.executable, "tests/regression_probe.py"),
        "test_source_ref": "tests/regression_probe.py",
        "failure_signature": signature,
    }
    red = capture_regression_phase(LeanRegressionOptions(phase="red", **options))
    assert red.status == "ready", red
    _write(root, "src/bug.py", green_source)
    green = capture_regression_phase(LeanRegressionOptions(phase="green", **options))
    assert green.status == "ready", green
    return RegressionEvidence.model_validate_json(
        (root / green.evidence_path).read_text("utf-8")
    )


def _seed_execution_loop(root: Path) -> None:
    artifacts = implementation_artifacts(root, "impl-test")
    impl_input = ImplementationInput(
        loop_id="impl-test",
        work_item_id="WI-TEST",
        work_item_path="specs/WI-TEST",
        spec_path="specs/WI-TEST/spec.md",
        plan_path="specs/WI-TEST/plan.md",
        tasks_path="specs/WI-TEST/tasks.md",
        design_contract_loop_id="design-test",
        work_type=WorkType.PRODUCTION_ISSUE,
        quality_profiles=["lean-code"],
        declared_scope=["src/bug.py", "tests/regression_probe.py"],
    )
    store = LoopArtifactStore(root)
    store.write_json_artifact(artifacts.input_path, impl_input)
    store.write_json_artifact(
        artifacts.loop_run_path,
        LoopRun(
            loop_id="impl-test",
            loop_type=LoopType.IMPLEMENTATION,
            input_digest=stable_artifact_digest(impl_input),
        ),
    )


def _file_digest(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _init_repo(root: Path, files: dict[str, str] | None = None) -> None:
    _git(root, "init", "--initial-branch=main")
    _git(root, "config", "user.email", "test@example.com")
    _git(root, "config", "user.name", "Test User")
    _write(root, "README.md", "# Test\n")
    for path, content in (files or {}).items():
        _write(root, path, content)
    _git(root, "add", ".")
    _git(root, "commit", "-m", "initial")


def _write(root: Path, relative: str, content: str) -> None:
    target = root / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, check=False
    )
    if result.returncode:
        raise AssertionError(result.stderr)
    return result.stdout.strip()
